# Generated by Django 2.1 on 2018-08-26 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='client',
            name='phone',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='client',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
