# Generated by Django 2.1 on 2018-08-26 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_currencytype_symbol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencytype',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
