# Generated by Django 2.1 on 2018-08-26 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20180826_1514'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('create_at', models.DateTimeField(auto_created=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('currencyType', models.ManyToManyField(to='api.CurrencyType')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Client')),
            ],
            options={
                'ordering': ('number',),
            },
        ),
        migrations.AlterUniqueTogether(
            name='account',
            unique_together={('id', 'number')},
        ),
    ]
