# Generated by Django 2.1 on 2018-08-26 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20180826_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterUniqueTogether(
            name='account',
            unique_together={('id', 'number', 'user')},
        ),
    ]
