# Generated by Django 2.1 on 2018-08-26 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20180826_1530'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='user',
            new_name='client',
        ),
        migrations.AlterField(
            model_name='currencytype',
            name='name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.RemoveField(
            model_name='account',
            name='currencyType',
        ),
        migrations.AlterUniqueTogether(
            name='account',
            unique_together={('id', 'number', 'client')},
        ),
    ]
