# Generated by Django 2.1 on 2018-08-26 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20180826_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='currencyType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='currencyType', to='api.CurrencyType'),
        ),
        migrations.AlterField(
            model_name='account',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client', to='api.Client'),
        ),
    ]
