# Generated by Django 2.1 on 2018-08-26 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20180826_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Client'),
        ),
        migrations.AlterField(
            model_name='account',
            name='currencyType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.CurrencyType'),
        ),
    ]
