# Generated by Django 2.1 on 2018-08-26 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20180826_1707'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('date', models.DateTimeField(auto_created=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('accountFrom', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='accountFrom', to='api.Account')),
                ('accountTo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='accountTo', to='api.Account')),
            ],
            options={
                'ordering': ('date',),
            },
        ),
        migrations.AlterUniqueTogether(
            name='transfer',
            unique_together={('id', 'accountFrom', 'accountTo')},
        ),
    ]
