# Generated by Django 2.1 on 2018-09-01 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20180831_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='account',
            name='number',
            field=models.IntegerField(editable=False),
        ),
    ]
