# Generated by Django 2.1 on 2018-09-01 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20180831_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='currency', to='api.CurrencyType'),
        ),
        migrations.AlterField(
            model_name='account',
            name='currencyType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='currencyType', to='api.CurrencyType'),
        ),
        migrations.AlterField(
            model_name='account',
            name='number',
            field=models.IntegerField(default=1, editable=False),
        ),
        migrations.AlterUniqueTogether(
            name='account',
            unique_together={('client', 'currencyType')},
        ),
    ]
