# Generated by Django 2.1 on 2018-09-02 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20180831_2340'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='transfer',
            unique_together={('id', 'accountFrom', 'accountTo', 'date')},
        ),
    ]
