# Generated by Django 2.1 on 2018-09-02 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20180901_2313'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='transfer',
            unique_together={('id',)},
        ),
    ]
