# Generated by Django 2.1 on 2018-09-03 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_auto_20180901_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='accountFrom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accountFrom', to='api.Account'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='accountTo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accountTo', to='api.Account'),
        ),
    ]
