# Generated by Django 2.1 on 2018-09-03 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_auto_20180903_1210'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ('id', 'number', 'client')},
        ),
    ]
